### ISSUE TITLE
confirm with the user before they switch to another mode

### ISSUE THREAD

**Issue by alexsan9051** [teoh4770/Pomotama#19] opened 2024-04-18 16:41 UTC
Steps to Reproduce:

1.  Start the timer for a specific task.
2. While the timer is counting down, click on another task
3. Timer resets

Not sure what the expected behavior is. Pomofocus.io continues the countdown after a popup asking if we want to switch tasks.

**Comment by teoh4770** [comment] 2024-04-18 16:47
Yes that's intended honestly.
But sure I can confirm with the user before they switch more.
Thanks for contributing

**Comment by alexsan9051** [comment] 2024-04-18 19:15
I'd love to give it a shot! @teoh4770

**Comment by teoh4770** [comment] 2024-04-18 19:58
@alexsan9051 assigned.
Remember to fork it and make pr after you finish it.
Let me know if you need any help.

**Comment by teoh4770** [comment] 2024-04-25 19:59
Reason we close this issue

"So I just saw this post about the reason we should against functions like alert and confirm. Basically we want the user to have fully control over the app itself, we don't want to promptly stop the user from using the app just to ask for confirmation(this is where I dislike about the original pomodoro app), unless (in my opinion) it is a destructive operation like delete a file permanently. "

**Closed by teoh4770** 2024-04-25 19:59 UTC
Labels: enhancement, p3 - Nice to have
